### ISSUE TITLE
Max Circle Size of 3 not mentioned in exercise documentation

### ISSUE THREAD

**Issue by FabianKollhoff** [tubs-alg/AlgLab-Summer-24#1]
https://github.com/tubs-alg/AlgLab-Summer-24/blame/e0c3e94a013391c7ea688881c7996a2c8502e767/sheets/01_cpsat/exercises/02_organ_donor_problem/README.md#L83-L88

The maximum circle size of 3 is not mentioned in the exercise.

**Comment by d-krupke** [comment]
Indeed! We original had a generic parameter, but simplified it to a constant. I will fix this. Thanks!

**Comment by d-krupke** [comment]
Fixed.
