### ISSUE TITLE
Wrong header size / missing hashtag

### ISSUE THREAD

**Issue by FabianKollhoff** [tubs-alg/AlgLab-Summer-24#2]
https://github.com/tubs-alg/AlgLab-Summer-24/blame/8e687510d613494459eb2668e3e4efa68854b23d/sheets/03_sat/exercises/02_hc_btsp/README.md#L53

**Comment by d-krupke** [comment]
Oh. We hoped that you were slower and we still had time to polish the third sheet a little. Have you already completed the first two sheets or are you only checking the third sheet out?
